services:
  postgres:
    image: postgres:16
    container_name: video_streamer_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: videouser
      POSTGRES_PASSWORD: videopassword
      POSTGRES_DB: videodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: